EdsTriathlonStuff/Models/CreateUserViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace EdsTriathlonStuff.Models
{
    public class CreateUserViewModel
    {
        public CreateUserViewModel() { }
        public CreateUserViewModel(ClaimsPrincipal identity) { }
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter valid email address.")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Please enter a valid email address")]
        [UIHint("email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a password.")]
        public string Password { get; set; }
        [Display(Name = "Confirm ")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        public List<string> RoleNames { get; set; }
        public List<bool> SelectedRoles { get; set; }
        public bool AllowRoleSelection { get; set; } = true;
    }
}

EdsTriathlonStuff/Controllers/CreateWorkoutController.cs
using EdsTriathlonStuff.App_Code;
using EdsTriathlonStuff.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EdsTriathlonStuff.Controllers
{
    public enum WorkoutSection { WarmUp, Main, CoolDown };
    [Authorize(Roles = "Coach, Athlete")]
    public class CreateWorkoutController : Controller
    {
        static SwimCreate model = null; // = new SwimCreate(5, 10, 5, new List<Workout>());
        private SwimDataContext context;
        private UserManager<AppUser> userManager;
        private static string UserId = string.Empty;
        public CreateWorkoutController(SwimDataContext ctx, UserManager<AppUser> usrMgr)
        {
            context = ctx;
            userManager = usrMgr;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var tempUserId = UserId;
            var current_User = userManager.GetUserAsync(HttpContext.User).Result;
            UserId = current_User.Id;

            if (model == null || tempUserId != UserId)
            {
                model = new SwimCreate(5, 10, 5, GetUsersWorkouts());

                model.CoachName = User.Identity.Name;
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Save(SwimCreate sc)
        {
            if (string.IsNullOrEmpty(UserId))
            {
                var current_User = userManager.GetUserAsync(HttpContext.User).Result;
                UserId = current_User.Id;
            }

            Workout wo = (from x in context.Workouts
                          where x.UserId == UserId && x.Name == sc.WorkoutName
                          select x).SingleOrDefault();// FirstOrDefault();

            //wo = context.Workouts.SingleOrDefault(b => b.UserId == UserId && b.Name == sc.WorkoutName);

            if (wo == null)
            {
                wo= new Workout
                {
                    AthleteName = sc.AthleteName,
                    CoolDownStepCount = sc.CoolDownEndSteps - sc.CoolDownBeginSteps,
                    WarmUpStepCount = sc.WarmUpEndSteps - sc.WarmUpBeginSteps,
                    MainStepCount = sc.MainEndSteps - sc.MainBeginSteps,
                    Description = sc.WorkoutDescription,
                    Name = sc.WorkoutName,
                    UserId = UserId,
                    TotalYards = sc.TotalYards,
                    TotalMeters = sc.TotalMeters
                };

                context.Workouts.Add(wo);

                //Save changes to get a valid wo.Id.
                context.SaveChanges();
            }
            else
            {
                wo.AthleteName = sc.AthleteName;
                wo.CoolDownStepCount = sc.CoolDownEndSteps - sc.CoolDownBeginSteps;
                wo.WarmUpStepCount = sc.WarmUpEndSteps - sc.WarmUpBeginSteps;
                wo.MainStepCount = sc.MainEndSteps - sc.MainBeginSteps;
                wo.Description = sc.WorkoutDescription;
                wo.Name = sc.WorkoutName;
                wo.UserId = UserId;
                wo.TotalYards = sc.TotalYards;
                wo.TotalMeters = sc.TotalMeters;
            }

            for (int i = 0; i < sc.SwimSets.Count; i++)
            {
                if (sc.SwimSets[i].RepCount > 0)
                {
                    WorkoutSection wos = WorkoutSection.CoolDown;
                    if (sc.SwimSets[i].StepNumber < wo.WarmUpStepCount)
                    {
                        wos = WorkoutSection.WarmUp;
                    }
                    else if (sc.SwimSets[i].StepNumber < (wo.MainStepCount + wo.WarmUpStepCount))
                    {
                        wos = WorkoutSection.Main;
                    }

                    SwimSet ss = (from x in context.SwimSets
                     where x.WorkoutId  == wo.Id && x.StepNumber == sc.SwimSets[i].StepNumber
                               select x).FirstOrDefault();

                    SwimSet ssNew = new SwimSet
                    {
                         Comment = sc.SwimSets[i].Comment,
                         Distance = sc.SwimSets[i].Distance,
                         RepCount = sc.SwimSets[i].RepCount,
                         Speed = sc.SwimSets[i].Speed,
                         Rest = sc.SwimSets[i].Rest,
                         StepNumber = i,
                         Total = sc.SwimSets[i].Total,
                         WorkoutId = wo.Id,
                         Group = wos
                    };

                    if (ss != null)
                    {
                        ss = ssNew;
                    }
                    else
                    {
                        context.SwimSets.Add(ssNew);
                    }
                }
            }

            context.SaveChanges();

            sc.SwimSpeedSelectList = sc.GetPaceSelectListItems();
            sc.SetDistanceSelectList = sc.GetSetDistanceSelectList();
            sc.Workouts = GetUsersWorkouts();
            sc.WorkoutId = wo.Id;
            model = sc;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Calculate(SwimCreate sc)
        {
            bool yards = true;
            string[] poolinfo = sc.PoolLength.Split(" ");
            int poolLength = Convert.ToInt32(poolinfo[0]);
            if (poolinfo[1] == "Meters")
            {
                yards = false;
            }
            const string endline = "\r\n";
            sc.Calculated = string.Empty;
            if (yards)
            {
                sc.Calculated = "Total Yards " + sc.TotalYards + endline;
            }
            else
            {
                sc.Calculated = "Total Meters " + sc.TotalMeters + endline;
            }
            sc.Calculated += "Warm Up" + endline;
            sc.Calculated += CreateSets(sc, poolLength, endline, WorkoutSection.WarmUp) + endline;
            sc.Calculated += "Main Set" + endline;
            sc.Calculated += CreateSets(sc, poolLength, endline, WorkoutSection.Main) + endline;
            sc.Calculated += "Cool Down" + endline;
            sc.Calculated += CreateSets(sc, poolLength, endline, WorkoutSection.CoolDown);
            sc.SwimSpeedSelectList = sc.GetPaceSelectListItems();
            sc.SetDistanceSelectList = sc.GetSetDistanceSelectList();
            sc.Workouts = GetUsersWorkouts();
            model = sc;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult LoadWorkout(int id)
        {
            if (string.IsNullOrEmpty(UserId))
            {
                var current_User = userManager.GetUserAsync(HttpContext.User).Result;
                UserId = current_User.Id;
            }

            Workout workout = (from x in context.Workouts
                               where x.UserId == UserId && x.Id == id
                               select x).FirstOrDefault();

            model = new SwimCreate(workout.WarmUpStepCount, 
                workout.MainStepCount, 
                workout.CoolDownStepCount,
                (from x in context.Workouts
                 where x.UserId == UserId
                 select x).ToList());
            model.UserName = User.Identity.Name;
            model.TotalMeters = workout.TotalMeters;
            model.TotalYards = workout.TotalYards;
            model.WorkoutDescription = workout.Description;
            model.AthleteName = workout.AthleteName;
            model.WorkoutName = workout.Name;
            model.CoachName = User.Identity.Name;

            IEnumerable<SwimSet> sets = (from y in context.SwimSets
                                         where y.WorkoutId == workout.Id
                                         select y);
            foreach (SwimSet ss in sets)
            {
                model.SwimSets[ss.StepNumber] = ss;
            }

            model.Workouts = GetUsersWorkouts();
            model.WorkoutId = workout.Id;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public string DeleteWorkout(Workout wo)
        {
            Workout woToDelete = (from x in context.Workouts
                                  where x.UserId == UserId && x.Id == wo.Id
                                  select x).FirstOrDefault();
            if (woToDelete != null)
            {
                context.Workouts.Remove(woToDelete);
                context.SaveChanges();
                model.Workouts = GetUsersWorkouts();
                return "success";
            }

            return "failed";
        }

        [HttpPost]
        public string RenameWorkout(Workout wo)
        {
            Workout woToRename = (from x in context.Workouts
                                  where x.UserId == UserId && x.Id == wo.Id
                                  select x).FirstOrDefault();
            if (woToRename != null)
            {
                woToRename.Name = wo.Name;
                context.SaveChanges();
                model.Workouts = GetUsersWorkouts();
                return "success";
            }

            return "failed";
        }

        private List<Workout> GetUsersWorkouts()
        {
            return (from x in context.Workouts
             where x.UserId == UserId
             select x).ToList<Workout>().ToList();
        }

        private static string CreateSets(SwimCreate sc, int poolLength, string endline, WorkoutSection section)
        {
            string retString = string.Empty;
            int beginStep = 0, endStep = 0;
            switch(section)
            {
                case WorkoutSection.WarmUp:
                    beginStep = sc.WarmUpBeginSteps;
                    endStep = sc.WarmUpEndSteps;
                    break;
                case WorkoutSection.Main:
                    beginStep = sc.MainBeginSteps;

EdsTriathlonStuff/Views/Shared/_AddSets.cshtml
@model SwimCreate;

<div style="margin-bottom: 25px;">
    <table>
        <tr>
            <td class="bold18">Repeat</td>
            <td class="bold18">Dist</td>
            <td class="bold18">Rest</td>
            <td class="bold18">Speed</td>
            <td class="bold18">Tot</td>
            <td class="bold18">Notes</td>
        </tr>
        @for (int i = (int)ViewData["begin"]; i < (int)ViewData["end"]; i++)
        {
        <tr>
            <td>
                @Html.TextBoxFor(m => m.SwimSets[i].RepCount,
                                  new
                                  {
                                      @type = "number",
                                      @min = 0,
                                      @class = "repsentry",
                                      @id = "reps" + i,
                                      @data_index = i
                                  })
            </td>
            <td>
                @Html.DropDownListFor(m => m.SwimSets[i].Distance, 
                                      Model.SetDistanceSelectList, 
                                      new
                                        {
                                            @class = "distselect",
                                            @id = "dist" + i,
                                            @data_index = i
                                        })
                @{
                    var divId = "div_content" + i;
                    var newOptionTxt = "newOptionTxt" + i;
                    <div id="@divId" style="display:none" data_index=@i>
                        <input id="@newOptionTxt" type="text" />
                        <input class="addvalue" type="button" value="AddNewItem" data_index=@i />
                    </div>
                }
            </td>
            <td>
                @Html.TextBoxFor(m => m.SwimSets[i].Rest,
                                 new
                                 {
                                     @type = "number",
                                     @min = 0,
                                     @class = "numentry",
                                     @data_index = i
                                 })
            </td>
            <td>
                @Html.DropDownListFor(m => m.SwimSets[i].Speed, Model.SwimSpeedSelectList, new { @class = "speedselect" })
            </td>
            <td>
                @Html.TextBoxFor(m => m.SwimSets[i].Total,
                                 new
                                 {
                                     @type = "number",
                                     @class = "readonlynumentry",
                                     @id = "tot" + i,
                                     @readonly = "true"
                                 })
            </td>
            <td>
                @Html.TextBoxFor(m => m.SwimSets[i].Comment,
                                 new { @class = "setnotes" })
            </td>
            @Html.HiddenFor(m => m.SwimSets[i].Id)
        </tr>
        }
    </table>
</div>

EdsTriathlonStuff/Views/Shared/_CreateUser.cshtml
@model CreateUserViewModel

<form asp-action="CreateUser" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" style="margin-left:26px;"> </label>
        <input asp-for="Name" class="text-box-wide" />
    </div>
    <div class="form-group">
        <label asp-for="Email" style="margin-left:26px;"> </label>
        <input asp-for="Email" class="text-box-wide" />
    </div>
    <div class="form-group">
        <label asp-for="Password"> </label>
        <input asp-for="Password" class="text-box-wide" type="password" />
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" style="margin-left:5px;"> </label>
        <input asp-for="ConfirmPassword" class="text-box-wide" type="password" />
    </div>
    @if (Model.AllowRoleSelection)
    {
        <div>
            <table class="roleTable" style="margin-bottom:25px; border-color:#808080;">
                @for (int i = 0; i < Model.RoleNames.Count; i++)
                {
                    @Html.HiddenFor(m => m.RoleNames[i])
                    <tr>
                        <td>@Html.LabelFor(m => m.SelectedRoles[i], Model.RoleNames[i])</td>
                        <td style="width:30px;">@Html.CheckBoxFor(m => m.SelectedRoles[i], new { @class = "checkbox-for" })</td>
                    </tr>

                }
            </table>
        </div>
    }
    <button type="submit" class="btn btn-primary" style="margin-left:34px;">CreateUser</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

EdsTriathlonStuff/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EdsTriathlonStuff</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EdsTriathlonStuff</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="CreateWorkout" asp-action="Index">Create Workout</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Login">Log In/Out</a></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EdsTriathlonStuff</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>